### ISSUE TITLE
UI Improvement - Wallet Balance Incorrect Sorting

### ISSUE THREAD

**Issue by mphonexay** [Switcheo/switcheo-neo#12]
![walletballance](https://user-images.githubusercontent.com/41430150/43035879-a921b77e-8cc4-11e8-8480-7a8c7453cd19.png)

Please see the attached file. I have just started to trade on Switcheo network. Great platform and I really would like to support your effort to make the product better. The attached screen show the incorrect sorting for all column label. Hope this help.

**Comment by HenryTimelessness** [comment]
Thanks for the information. Closing this as unrelated to contract.
You can give your feedback in support@switcheo.network
