### ISSUE TITLE
UI Improvement - Your Transactions - Post Cost Column

### ISSUE THREAD

**Issue by mphonexay** [Switcheo/switcheo-neo#13]
![your transaction - post cost column](https://user-images.githubusercontent.com/41430150/43035993-777c3080-8cc6-11e8-946f-5bcdf750c5b8.png)

This is a enhance to show the current commit NEO or Post Processing cost of NEO. In my opinion, showing 0.0000000 value can be misleading and it does not help remind the user how much NEO is being committed to this current purchase order.

**Comment by HenryTimelessness** [comment]
Thanks for the information. Closing this as unrelated to contract.
You can give your feedback in support@switcheo.network
