### ISSUE TITLE
UI Improvement - Mismatch status

### ISSUE THREAD

**Issue by mphonexay** [Switcheo/switcheo-neo#14]
![your transaction - mismatched status](https://user-images.githubusercontent.com/41430150/43036054-e56cdfee-8cc7-11e8-8e19-33947290e7c2.png)

Could this be due to hard-coded string? You should create a mapping of display string value to some integer value corresponding to each status. This may give you the flexibility to later added support to other languages. This way the back end mapping never need to be change.

**Comment by HenryTimelessness** [comment]
Closing this as unrelated to contract.
