### ISSUE TITLE
UI Improvement - Your Transaction - Dynamically closing the drop down

### ISSUE THREAD

**Issue by mphonexay** [Switcheo/switcheo-neo#16]
![your transaction - dynamically closing the drop down](https://user-images.githubusercontent.com/41430150/43036127-17658450-8cc9-11e8-87c7-2a87f9de74d5.png)

Minor enhancement to delivery good user experience. If user click on the drop down than clicking elsewhere, than the drop down should automatically close.

**Comment by HenryTimelessness** [comment]
closing as unrelated to contract
