### ISSUE TITLE
division-with-remainder result

### ISSUE THREAD

**Issue by NeoGreenThumb** [Switcheo/switcheo-neo#17]
Hi Switcheo team,

I have asked Neo Discord support why it is that when i place a maker order without fees i still end up with .99999999 of a token when it is filled 100% and i ordered a whole number.

Someone mentioned that maybe it would be possible to employ some code to fix the division-with-remainder result so that orders would be filled completely.

Is this something that is under your attention for an upcoming update?

**Comment by HenryTimelessness** [comment]
This is an order matching and not a smart contract issue. This should have been fixed separately already.
